# Generated by Django 4.2.9 on 2024-02-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='room_type',
            new_name='hall_type',
        ),
    ]
