# Generated by Django 4.2.9 on 2024-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_rename_room_type_hall_hall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halltype',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
