# Generated by Django 4.2.9 on 2024-02-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_rename_room_type_hall_hall_type'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes_movie', to='hall.hall'),
        ),
    ]
