# Generated by Django 4.2.9 on 2024-02-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_rename_room_type_hall_hall_type'),
        ('movies', '0003_remove_showtimes_hall_remove_showtimes_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieformat'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movieformat',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.cinema'),
        ),
    ]
