# Generated by Django 4.2.9 on 2024-02-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_format_showtimes_hall_showtimes_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинотеатр'},
        ),
    ]
